version: "3.7"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 443:443
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry